### ISSUE TITLE
Configuration Issue

### ISSUE THREAD

**Issue by toddca** [DarthWeirdo/dotTraceCI#6]
We cannot seem to configure the Threshold values if our namespace is “Drax.Test.Integration.Core.Services” – it seems the plug-in only allows a single label namespace. Is this really the case or are we doing something wrong here?

Here is our entire perf threshold config:
Drax.Test.Integration.Core.Services.FormProcessing.FormProcessingTests.Can_Import_Prior_Year_Tax_Return F15 0

NameSpace: Drax.Test.Integration.Core.Services.FormProcessing
Class: FormProcessingTests
Method: Can_Import_Prior_Year_Tax_Return

**Comment by DarthWeirdo** [comment]
This is a bug in 0.9.1. Please use the 0.9.0 version. Will fix it ASAP. Sorry for the inconvenience.

**Comment by toddca** [comment]
So did this get fixed in the latest bits?
